 // src/ContentIncomes.jsx
import React, { useState } from 'react';

const ContentIncomes = () => {
  const [isFormOpen, setIsFormOpen] = useState(false); // état pour le popover
  const [formData, setFormData] = useState({
    amount: '',
    date: '',
    source: '',
    description: '',
  });

  const incomesColumns = [
    { name: 'Id' },
    { name: 'Amount' },
    { name: 'Date' },
    { name: 'Source' },
    { name: 'Description', optional: true },
    { name: 'Creation Date', autoGenerated: true },
  ];

  const handleChange = (e) => {
    setFormData({ ...formData, [e.target.name]: e.target.value });
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    console.log('Nouvelle ligne:', formData);
    setIsFormOpen(false);
    setFormData({ amount: '', date: '', source: '', description: '' });
  };

  return (
    <div className="w-full mt-[6vw] flex flex-col items-center">
      {/* Titre du tableau */}
      <h1 className="text-2xl md:text-3xl font-bold mb-6 text-gray-800">
        Income Tracking Table
      </h1>

      {/* Tableau */}
      <div className="w-[80vw] overflow-auto shadow-lg rounded-lg border border-gray-300">
        <table className="w-full table-auto border-collapse">
          <thead className="bg-gray-200 sticky top-0 z-10">
            <tr>
              {incomesColumns.map((col, index) => (
                <th
                  key={index}
                  className="p-4 border-b border-gray-300 text-center font-semibold"
                >
                  {col.name}
                </th>
              ))}
            </tr>
          </thead>
          <tbody className="bg-white">
            {/* Ligne du bouton centré */}
            <tr>
              <td colSpan={6} className="p-4 flex justify-center relative">
                <button
                  onClick={() => setIsFormOpen(!isFormOpen)}
                  className="bg-blue-500 hover:bg-blue-600 text-white font-semibold py-2 px-6 rounded-full shadow-md flex items-center justify-center gap-2 transition-all transform hover:scale-105"
                >
                  <span className="text-xl font-bold">+</span>
                  <span>Add</span>
                </button>

                {/* Popover du formulaire */}
                {isFormOpen && (
                  <div className="absolute top-full mt-2 bg-white shadow-lg rounded-lg p-4 w-[400px] z-50 border border-gray-300">
                    <h2 className="text-lg font-bold mb-2">Add Income</h2>
                    <form onSubmit={handleSubmit} className="flex flex-col gap-2">
                      <input
                        type="number"
                        name="amount"
                        placeholder="Amount"
                        value={formData.amount}
                        onChange={handleChange}
                        className="border p-2 rounded"
                        required
                      />
                      <input
                        type="date"
                        name="date"
                        value={formData.date}
                        onChange={handleChange}
                        className="border p-2 rounded"
                        required
                      />
                      <input
                        type="text"
                        name="source"
                        placeholder="Source"
                        value={formData.source}
                        onChange={handleChange}
                        className="border p-2 rounded"
                        required
                      />
                      <input
                        type="text"
                        name="description"
                        placeholder="Description (optional)"
                        value={formData.description}
                        onChange={handleChange}
                        className="border p-2 rounded"
                      />
                      <div className="flex justify-end gap-2 mt-2">
                        <button
                          type="button"
                          onClick={() => setIsFormOpen(false)}
                          className="bg-gray-300 hover:bg-gray-400 text-black px-4 py-2 rounded"
                        >
                          Cancel
                        </button>
                        <button
                          type="submit"
                          className="bg-blue-500 hover:bg-blue-600 text-white px-4 py-2 rounded"
                        >
                          Save
                        </button>
                      </div>
                    </form>
                  </div>
                )}
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  );
};

export default ContentIncomes;
